<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>arnold</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>CFBundleDocumentTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>dsk</string>
				<string>DSK</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>disk.icns</string>
			<key>CFBundleTypeName</key>
			<string>Arnold Disk Image</string>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>CpDk</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Viewer</string>
			<key>LSIsAppleDefaultForType</key>
			<true/>
			<key>LSItemContentTypes</key>
			<array>
				<string>com.thacker.arnold.dsk</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
				<array>
				<string>cpr</string>
				<string>CPR</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>cartridge.icns</string>
			<key>CFBundleTypeName</key>
			<string>Arnold CPC+ Cartridge</string>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>CpCt</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Viewer</string>
			<key>LSItemContentTypes</key>
			<array>
				<string>com.thacker.arnold.cpr</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
				<array>
				<string>sna</string>
				<string>SNA</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>snapshot.icns</string>
			<key>CFBundleTypeName</key>
			<string>Arnold Freeze State</string>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>CpSn</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Viewer</string>
			<key>LSItemContentTypes</key>
			<array>
				<string>com.thacker.arnold.sna</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>tzx</string>
				<string>TZX</string>
				<string>cdt</string>
				<string>CDT</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>tape.icns</string>
			<key>CFBundleTypeName</key>
			<string>Arnold Tape Image</string>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>CpTp</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Viewer</string>
			<key>LSItemContentTypes</key>
			<array>
				<string>com.thacker.arnold.cdt</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array/>
			<key>CFBundleTypeIconFile</key>
			<string>Arnold_Expansion.icns</string>
			<key>CFBundleTypeName</key>
			<string>Arnold Expansion ROM</string>
			<key>CFBundleTypeOSTypes</key>
			<array>
				<string>CpEx</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Viewer</string>
			<key>LSItemContentTypes</key>
			<array>
				<string>com.thacker.arnold.rom</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>csw</string>
				<string>CSW</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>csw</string>
			<key>CFBundleTypeName</key>
			<string>Amstrad CPC Tape Image</string>
			<key>CFBundleTypeRole</key>
			<string>Viewer</string>
			<key>LSItemContentTypes</key>
			<array>
				<string>com.thacker.arnold.csw</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeExtensions</key>
			<array>
				<string>wav</string>
				<string>WAV</string>
			</array>
			<key>CFBundleTypeIconFile</key>
			<string>blank</string>
			<key>CFBundleTypeName</key>
			<string>Amstrad CPC Tape Image</string>
			<key>CFBundleTypeRole</key>
			<string>Viewer</string>
			<key>LSItemContentTypes</key>
			<array>
				<string>com.thacker.arnold.wav</string>
			</array>
		</dict>
	</array>
	<key>CFBundleGetInfoString</key>
	<string>Amstrad CPC/CPC+ Emulator Copyright © 2015 Kevin Thacker</string>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2015 Kevin Thacker</string>
	<key>CFBundleIconFile</key>
	<string>arnold.icns</string>
	<key>CFBundleIdentifier</key>
	<string>com.thacker.arnold</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleLongVersionString</key>
	<string>1.1.2</string>
	<key>CFBundleName</key>
	<string>Arnold</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.1.2</string>
	<key>CFBundleSignature</key>
	<string>ArKT</string>
	<key>CFBundleVersion</key>
	<string>1.1.2</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.games</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.6</string>
	<key>LSArchitecturePriority</key>
	<array>
		<string>arm64</string>
		<string>x86_64</string>
	</array>
	<key>LSSupportsOpeningDocumentsInPlace</key>
	<string>YES</string>
	<key>UTExportedTypeDeclarations</key>
	<array>
		<dict>
			<key>UTTypeConformsTo</key>
			<array>
				<string>public.data</string>
				<string>public.content</string>
			</array>
			<key>UTTypeDescription</key>
			<string>Amstrad CPC+ Cartridge Image</string>
			<key>UTTypeIdentifier</key>
			<string>com.thacker.arnold.cartridge</string>
		</dict>
		<dict>
			<key>UTTypeConformsTo</key>
			<array>
				<string>public.data</string>
				<string>public.content</string>
			</array>
			<key>UTTypeDescription</key>
			<string>Amstrad CPC storage</string>
			<key>UTTypeIdentifier</key>
			<string>com.thacker.arnold.storage</string>
		</dict>
		<dict>
			<key>UTTypeConformsTo</key>
			<array>
				<string>public.data</string>
				<string>public.content</string>
			</array>
			<key>UTTypeDescription</key>
			<string>Amstrad CPC Snapshot</string>
			<key>UTTypeIdentifier</key>
			<string>com.thacker.arnold.snapshot</string>
		</dict>
		<dict>
			<key>UTTypeConformsTo</key>
			<array>
				<string>public.audio</string>
			</array>
			<key>UTTypeDescription</key>
			<string>ZX Spectrum Tape Image</string>
			<key>UTTypeIdentifier</key>
			<string>com.thacker.arnold.tape</string>
		</dict>
		<dict>
			<key>UTTypeConformsTo</key>
			<array>
				<string>com.thacker.arnold.storage</string>
			</array>
			<key>UTTypeDescription</key>
			<string>Amstrad CPC Disk Image</string>
			<key>UTTypeIdentifier</key>
			<string>com.thacker.arnold.dsk</string>
			<key>UTTypeReferenceURL</key>
			<string>http://www.cpctech.org.uk/docs/extdsk.html</string>
			<key>UTTypeTagSpecification</key>
			<dict>
				<key>public.filename-extension</key>
				<array>
					<string>dsk</string>
				</array>
			</dict>
		</dict>
		<dict>
			<key>UTTypeConformsTo</key>
			<array>
				<string>com.thacker.arnold.snapshot</string>
			</array>
			<key>UTTypeDescription</key>
			<string>Amstrad CPC Snapshot</string>
			<key>UTTypeIdentifier</key>
			<string>com.thacker.sna</string>
			<key>UTTypeReferenceURL</key>
			<string>http://www.cpctech.org.uk/docs/snapshot.html</string>
			<key>UTTypeTagSpecification</key>
			<dict>
				<key>public.filename-extension</key>
				<array>
					<string>sna</string>
				</array>
			</dict>
		</dict>
		<dict>
			<key>UTTypeConformsTo</key>
			<array>
				<string>com.thacker.arnold.tape</string>
			</array>
			<key>UTTypeDescription</key>
			<string>Amstrad CPC Tape Image</string>
			<key>UTTypeIdentifier</key>
			<string>com.thacker.arnold.tzx</string>
			<key>UTTypeReferenceURL</key>
			<string>http://www.worldofspectrum.org/TZXformat.html</string>
			<key>UTTypeTagSpecification</key>
			<dict>
				<key>public.filename-extension</key>
				<array>
					<string>tzx</string>
				</array>
			</dict>
		</dict>
		<dict>
			<key>UTTypeConformsTo</key>
			<array>
				<string>com.thacker.arnold.cartridge</string>
			</array>
			<key>UTTypeDescription</key>
			<string>Amstrad CPC+ Cartridge Image</string>
			<key>UTTypeIdentifier</key>
			<string>com.thacker.arnold.cpr</string>
			<key>UTTypeReferenceURL</key>
			<string>http://www.cpctech.org/docs/cpr.html</string>
			<key>UTTypeTagSpecification</key>
			<dict>
				<key>public.filename-extension</key>
				<array>
					<string>cpr</string>
				</array>
			</dict>
		</dict>
		<dict>
			<key>UTTypeConformsTo</key>
			<array>
				<string>com.thacker.arnold.tape</string>
			</array>
			<key>UTTypeDescription</key>
			<string>Amstrad CPC Tape Image</string>
			<key>UTTypeIdentifier</key>
			<string>com.thacker.arnold.cdt</string>
			<key>UTTypeReferenceURL</key>
			<string>http://www.worldofspectrum.org/TZXformat.html</string>
			<key>UTTypeTagSpecification</key>
			<dict>
				<key>public.filename-extension</key>
				<array>
					<string>cdt</string>
				</array>
			</dict>
		</dict>
	</array>
</dict>
</plist>
