.\" -*- nroff -*-
.\"
.\" arnold.1: Arnold man page
.\" Copyright (c) 2001-2015 Kevin Thacker
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Author contact information:
.\"
.\" E-mail: kev@cpcfreak.co.uk
.\"
.\"
.TH arnold 1 "18 July 2015" "Version 1.0" "Emulators"
.SH NAME
arnold \(em Amstrad CPC/Plus emulator
.SH SYNOPSIS
.B arnold
.RI [ options ]
.P
.SH DESCRIPTION
Arnold is an Amstrad CPC, Amstrad Plus, GX4000, KC Compact and Aleste 520EX emulator.
.PP
The KC Compact is a clone made in East Germany.
The Aleste 520EX is a clone made in Russia with a special MSX-like mode.
.SH OPTIONS
.B \-\-drivea
.RS
Specify a disc image to insert into drive A
.RE
.PP
.B \-\-driveb
.RS
Specify a disc image to insert into drive B
.RE
.PP
.B \-\-diska
.RS
Specify a disc image to insert into drive A
.RE
.PP
.B \-\-diskb
.RS
Specify a disc image to insert into drive B
.RE
.PP
.B \-\-diskc
.RS
Specify a disc image to insert into drive C
.RE
.PP
.B \-\-diskd
.RS
Specify a disc image to insert into drive D
.RE
.PP
.B \-\-cart
.RS
Specify a GX4000/Amstrad Plus cartridge image to start . 
.RE
.PP
.B \-\-snapshot
.RS
Specify a memory snapshot to start.
.RE
.PP
.B \-\-autotype
.RS
Specify text to automatically type when the computer has booted.
.RE
.PP
.B \-\-autostart
.RS
Specify a file to auto start, it may be a disk, cassette, cartridge or binary file.
.RE
.PP
.SH FILES
.I "~/.Arnold"
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
Kevin Thacker (kev@cpcfreak.co.uk)
.SH COPYRIGHT
